### ISSUE TITLE
Missing variable for translation

### ISSUE THREAD

**Issue by payagej** [rocky-linux/rockylinux.org-gatsby#108]
## Describe the bug

On the footer of the website you have 3 links that aren't translated. After check on the translation.json and the website code, these links name are hardcoded into the website.
 
- `Community Charter`
- `Organizational Structure`
- `Privacy Policy`

## To Reproduce

1. Go the https://rockylinux.org/ 
2. Select any language 
3. Go to the footer section of the page
4. See that it's still write in english.

## Expected behavior

These links should be translated

**Comment by robinduerhager** [comment]
That is also true for the `See More` and `See All` Buttons on the Homepage.
