### ISSUE TITLE
Links have the prefix 'links.' based on chosen language

### ISSUE THREAD

**Issue by robinduerhager** [rocky-linux/rockylinux.org-gatsby#113]
## Describe the bug
Based on the chosen language, some Links on the Homepage have a `links.` prefix, e.g.: `links.download` in the Download Button or `links.partners` in the footer. This is somehow not the case for the french and english version of the website.

## To Reproduce

1. Go to 'https://rockylinux.org/'
2. Change the language on the bottom to any except french or english
3. Look at the Download Button and the footer

## Expected behavior
Links should be displayed without the `links.` prefix, e.g.: `links.download` should be `Download`.

## Screenshots
![Homepage Download Buttons Error](https://user-images.githubusercontent.com/18482238/118625184-134ca900-b7ca-11eb-9e83-9932b0a7eebb.png)
![Homepage Footer Links Error](https://user-images.githubusercontent.com/18482238/118625253-23648880-b7ca-11eb-9dc5-b640e810659e.png)

## Device Information

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: firefox
- Version: 88.0.1

**Smartphone (please complete the following information):**

- Device: iPhone SE 2020
- OS: [e.g. iOS 14.5.1
- Browser: firefox daylight
- Version: 33.1

**Comment by payagej** [comment]
Hello ! 
If you don't plan to do a pull request to fix these, feel free to send them here with good translation and the language you are using so a contributor can do the translation !
