### ISSUE TITLE
Lower blockquote bar brightness on dark theme

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-gatsby#121]
At the moment, the bar next to the text on a quote is really bright. We should lower this to a more grey colour in my opinion

**Comment by NebraskaCoder** [comment]
Can you post a screenshot (or page) of where you are seeing this?

**Comment by hbjydev** [comment]
![image](https://user-images.githubusercontent.com/22327045/121775340-dd0f0900-cb7e-11eb-91ef-2132d8a8f7fe.png)

https://rockylinux.org/news/rocky-linux-8-4-rc1-release/

@NebraskaCoder I feel like this should be closer to grey than white.

**Comment by NebraskaCoder** [comment]
@hbjydev I didn't see it at first (nor read the title) as I don't have dark theme enabled on my phone. Once I enabled it, I was able to see what you are talking about.

**Comment by NebraskaCoder** [comment]
I am not able to get this to work as the prose-dark class is overwriting any text colors I try to change.
