### ISSUE TITLE
warn ESLintError: onBlur must be used instead of onchange, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users  jsx-a11y/no-onchange

### ISSUE THREAD

**Issue by NebraskaCoder** [rocky-linux/rockylinux.org-gatsby#137]
## Describe the bug

When building the Gatsby site, the following warning (non-blocking) appears on the output.

```
warn ESLintError:
\rockylinux.org\src\components\footer\index.jsx
  180:13  warning  onBlur must be used instead of onchange, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users  jsx-a11y/no-onchange
```

## To Reproduce

1. Issue gatsby develop
2. See warning in the output

## Expected behavior

No warnings should appear.

**Comment by hbjydev** [comment]
See #167. We're currently blocked on this but obviously would still like to resolve this :)
