### ISSUE TITLE
Add Microsoft as Principal Sponsor

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#152]
Please add Microsoft's logo to our rotating banner on the main landing page, along with their logo on the Sponsors page. This is the quote to use for them:

> Linux is the fastest growing platform on Azure, running in over half of VM cores. For well over a decade, Microsoft has been investing on Linux, and with partnerships being a central pillar of Microsoft’s open source strategy we collaborate with RESF and the broader Rocky Linux ecosystem to ensure customers have an increasing set of options to deploy Linux workloads on Azure in a supported, managed and secure way.

For their logo, please see: https://web.tresorit.com/l/C53Vf#tkW259swcvDyYfzp7u1neQ

**Comment by brianclemens** [comment]
Added in #154
