### ISSUE TITLE
Add link to official AMI on Downloads page

### ISSUE THREAD

**Issue by brianclemens** [rocky-linux/rockylinux.org-gatsby#172]
Links to [official AMIs](https://aws.amazon.com/marketplace/seller-profile?id=01538adc-2664-49d5-b926-3381dffce12d) should be added to the Downloads page.

**Comment by tcooper** [comment]
Here is the list of AMIs I was able to pull for the x86_64 AMI...

| Version         | Region         | Architecture | AMI ID                | Deploy Link                                                                                                               |
|-----------------|----------------|--------------|-----------------------|---------------------------------------------------------------------------------------------------------------------------|
| Rocky Linux 8.4 | us-west-1      | x86_64       | ami-0f91bc0c77f3dea4c | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=us-west-1#LaunchInstanceWizard:ami=ami-0f91bc0c77f3dea4c)      |
| Rocky Linux 8.4 | us-west-2      | x86_64       | ami-0e3654b38a33c9ca5 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=us-west-2#LaunchInstanceWizard:ami=ami-0e3654b38a33c9ca5)      |
| Rocky Linux 8.4 | us-east-1      | x86_64       | ami-02628ddf3745c6dda | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-02628ddf3745c6dda)      |
| Rocky Linux 8.4 | us-east-2      | x86_64       | ami-086586d173a744e81 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=us-east-2#LaunchInstanceWizard:ami=ami-086586d173a744e81)      |
| Rocky Linux 8.4 | af-south-1     | x86_64       | tbd                   | tbd                                                                                                                       |
| Rocky Linux 8.4 | ap-east-1      | x86_64       | tbd                   | tbd                                                                                                                       |
| Rocky Linux 8.4 | ap-south-1     | x86_64       | ami-006b289f5107d2a13 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=ap-south-1#LaunchInstanceWizard:ami=ami-006b289f5107d2a13)     |
| Rocky Linux 8.4 | ap-northeast-1 | x86_64       | ami-0ddf5ff463ff76656 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=ap-northeast-1#LaunchInstanceWizard:ami=ami-0ddf5ff463ff76656) |
| Rocky Linux 8.4 | ap-northeast-2 | x86_64       | ami-053101624580f0052 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=ap-northeast-2#LaunchInstanceWizard:ami=ami-053101624580f0052) |
| Rocky Linux 8.4 | ap-northeast-3 | x86_64       | ami-0c43c9904c364f13d | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=ap-northeast-3#LaunchInstanceWizard:ami=ami-0c43c9904c364f13d) |
| Rocky Linux 8.4 | ap-southeast-1 | x86_64       | ami-02404605a9a99ed58 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=ap-southeast-1#LaunchInstanceWizard:ami=ami-02404605a9a99ed58) |
| Rocky Linux 8.4 | ap-southeast-2 | x86_64       | ami-084694f3a1c5fdef6 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=ap-southeast-2#LaunchInstanceWizard:ami=ami-084694f3a1c5fdef6) |
| Rocky Linux 8.4 | ca-central-1   | x86_64       | ami-06e4adca178dfc59a | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=ca-central-1#LaunchInstanceWizard:ami=ami-06e4adca178dfc59a)   |
| Rocky Linux 8.4 | eu-north-1     | x86_64       | ami-0f2c0f2f6b767fdaa | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=eu-north-1#LaunchInstanceWizard:ami=ami-0f2c0f2f6b767fdaa)     |
| Rocky Linux 8.4 | eu-south-1     | x86_64       | tbd                   | tbd                                                                                                                       |
| Rocky Linux 8.4 | eu-central-1   | x86_64       | ami-0991f79c5232dc740 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=eu-central-1#LaunchInstanceWizard:ami=ami-0991f79c5232dc740)   |
| Rocky Linux 8.4 | eu-west-1      | x86_64       | ami-00c4135a4e9b7c9db | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=eu-west-1#LaunchInstanceWizard:ami=ami-00c4135a4e9b7c9db)      |
| Rocky Linux 8.4 | eu-west-2      | x86_64       | ami-093547c220280b79c | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=eu-west-2#LaunchInstanceWizard:ami=ami-093547c220280b79c)      |
| Rocky Linux 8.4 | eu-west-3      | x86_64       | ami-00e9e5957ab5caeb4 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=eu-west-3#LaunchInstanceWizard:ami=ami-00e9e5957ab5caeb4)      |
| Rocky Linux 8.4 | me-south-1     | x86_64       | tbd                   | tbd                                                                                                                       |
| Rocky Linux 8.4 | sa-east-1      | x86_64       | ami-0ab5e8fd80db76070 | [Deploy](https://console.aws.amazon.com/ec2/v2/home?region=sa-east-1#LaunchInstanceWizard:ami=ami-0ab5e8fd80db76070)      |

**Comment by lisenet** [comment]
This has already been requested elsewhere, but I'll post it on this issue just in case: could we have a column with AWS marketplace products codes added as well please? It's useful if you use Terraform to deploy your infrastructure.

**Comment by ccg-mcarifio** [comment]
Could you also indicate the default username for uid 1000 is `rocky`. I know it's similar to centos, but it could also be `ec2-user` or even `root`. I can create a new issue if that's easier to track.

**Comment by chicks-net** [comment]
This ended up at https://rockylinux.org/cloud-images/
