### ISSUE TITLE
Update Fastly listing on Partner page w/ blurb

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#175]
Can we please update Fastly's logo with the following blurb so they have prominent placement? 

> With Fastly’s powerful edge cloud platform, developers get the tools they need to build the most groundbreaking apps — all optimized for speed, security, and scale — so businesses can effectively transform to compete in today’s markets. Together, we’re building the future of the web.

This is pulled from their website. Thanks!

**Comment by brianclemens** [comment]
Added in 2b07029a4383de7876b5ccedcb4cd3a2637d6e18
