### ISSUE TITLE
Add logo to Sponsors page for Seagate

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#176]
We have a new Tier 4 sponsor, Seagate Federal. Tier 4 sponsors don't get their logo added to the banner on the main page, but they get a logo added to the Sponsors page. Please use one of the attached (whichever looks best) to add them. Thank you!

https://web.tresorit.com/l/vQy02#oD6qduzrWitG6SmxPp6i4g

**Comment by antrikshmalik** [comment]
What should be the grade of a tier 4 sponsor? Is it the same as a principal sponsor? And from where should the description be added?
