### ISSUE TITLE
Add link to errata

### ISSUE THREAD

**Issue by brianclemens** [rocky-linux/rockylinux.org-gatsby#177]
A link to security advisories / errata (https://errata.rockylinux.org) should be placed somewhere prominent.

**Comment by brianclemens** [comment]
The errata link is no longer present anywhere. Perhaps it could be added to the documentation menu?

**Comment by FoggyMtnDrifter** [comment]
Thanks for re-opening this, @brianclemens. I somehow missed that. I'll get that added sometime this week if no one else gets to it before I do.
