### ISSUE TITLE
Fosshost logo unreadable in light mode

### ISSUE THREAD

**Issue by brianclemens** [rocky-linux/rockylinux.org-gatsby#185]
In light mode, the Fosshost logo appears almost completely grey.

<img width="128" alt="Screen Shot 2021-08-14 at 9 21 28" src="https://user-images.githubusercontent.com/13581364/129428790-be591446-6994-49a7-82ee-7e498291a5c7.png">

**Comment by zeeshanjamal16** [comment]
@brianclemens PR for this issue - https://github.com/rocky-linux/rockylinux.org/pull/192

**Comment by brianclemens** [comment]
Thanks @IYaksha!
