### ISSUE TITLE
Update Fastly blurb

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#187]
Fastly came back with a blurb they would like us to use for them. Please update it to read:

> Fastly’s edge cloud platform enables customers to create great digital experiences quickly, securely, and reliably by processing, serving, and securing our customers’ applications as close to their end-users as possible — at the edge of the internet.

**Comment by brianclemens** [comment]
cbb440b74bdf73c1f2c93494613932d834e7a2c7
