### ISSUE TITLE
Please add anchor link to  Rocky FAQ

### ISSUE THREAD

**Issue by tjyang** [rocky-linux/rockylinux.org-gatsby#189]
**Is your feature request related to a problem? Please describe.**
Yes, not able to give out exact URL for a specific FAQ on https://rockylinux.org/faq/

**Describe the solution you'd like**
Please add anchor link to each Question.

**Describe alternatives you've considered**

**Additional context**
So we can post exact URL to new comer for their question.

**Comment by tjyang** [comment]
@ressonix , I am still not able to use URL to point to following FAQ directly.  Is #191 really got pushed out, Should I wait for a while  ?

![image](https://user-images.githubusercontent.com/378638/131019817-087bbc32-51bc-4034-b56a-a831e6dbbe22.png)

**Comment by FoggyMtnDrifter** [comment]
Hey there, @tjyang! The anchor tags are there, you have to append `#faq-{insert faq number}` after the URL. For instance, `https://rockylinux.org/faq/#faq-5`. Hope that helps!

**Comment by tjyang** [comment]
@ressonix , thanks for the #faq-5 example. Is it possible that you can add a  small icon to link to #faq-5 at front of a question ? 
This way, user like me can click on 100th FAQ without counting.

**Comment by tjyang** [comment]
@ressonix 
See link icon example in  following screenshot from other doc.
https://bitwarden.com/help/article/releasenotes/#2021-01-19

![image](https://user-images.githubusercontent.com/378638/132736125-37dbbe82-7bc3-4242-aa4a-80973f860d2f.png)

**Comment by tjyang** [comment]
- Another example from rocky site.
![image](https://user-images.githubusercontent.com/378638/132995625-cdf1d11a-22e5-4347-95fd-80ae1fb84ed6.png)
