### ISSUE TITLE
Make AMIs available as public AMIs 

### ISSUE THREAD

**Issue by mikedlr** [rocky-linux/rockylinux.org-gatsby#197]
## Description

Currently the official Amazon Machine Images (AMIs) are available only in the AWS market place.  That's a fine place but it means that the images aren't available until a user subscribes, so if they search for Rocky by default they get unofficial images which may or may not be updated later. 

Please publish the AMIs as public ones.  See also https://github.com/rocky-linux/rockylinux.org/issues/172 and https://forums.rockylinux.org/t/rocky-linux-official-aws-ami/3049/14 (which also states that this would be useful when creating an instance using Terraform) 

I'm happy to do this but lack the appropriate access right now.

**Comment by rlhennig** [comment]
Can you elaborate a little more please? When I search on the Marketplace I see our official ones popping up right away at the top: https://aws.amazon.com/marketplace/search/results?searchTerms=rocky+linux

Screenshot: https://web.tresorit.com/l/RUUKe#2yhxqehFi-5mt-EwTfBt9w

I might not be understanding you

**Comment by mikedlr** [comment]
The market place is not the normal place that people find images.  They find them when they start a machine and then there a set of public images which you don't have to subscribe to at all.

If you don't have a marketplace subscription to the rocky linux images then you can't access the which is a pain.

1) go to AWS EC2 console https://us-east-2.console.aws.amazon.com/ec2/v2/home?region=us-east-2#Instances:
2) click launch instance
3) type rocky in search and then enter

expected result:
official rocky linux image shows up

actual result
no images visible and links to some groups in which there are unoffical images.

compare and contrast with typing "windows"

**Comment by davidiglesiasb** [comment]
You can use the following as a reference:

https://wiki.centos.org/Cloud/AWS
https://cloud-images.ubuntu.com/locator/ec2/

**Comment by ziggythehamster** [comment]
Marketplace AMIs also pollute images with product codes and so if you want to do something that would normally be disallowed on marketplace AMI derived images (like share between accounts or run on an instance type that hasn't been allowlisted by the marketplace listing), you have to boot an instance, mount a blank volume and your image, then dd from one to the other. This is not ideal :).

**Comment by mikedlr** [comment]
My account access is finally fixed so I have now put this into the official rocky bug tracker  - https://bugs.rockylinux.org/show_bug.cgi?id=171

**Comment by FoggyMtnDrifter** [comment]
Thanks, @mikedlr! Seeing as to how this issue is related to AMIs and not necessarily our website and you've already put it into the bug tracker, I'm going to go ahead and close this issue. Note we'll still be adding a list of AMIs to the site via #172.

**Comment by boegel** [comment]
I'm getting a 404 now on https://bugs.rockylinux.org/show_bug.cgi?id=171, is that expected?

What's the right place to follow up on this?

**Comment by FoggyMtnDrifter** [comment]
We switched from Bugzilla to Mattermost @boegel and I'm not certain if everything was migrated over. @NeilHanlon might be able to chime in on this one.

**Comment by bputt-e** [comment]
@boegel @NeilHanlon for reference, this is effectively what happens when I try to copy an AMI. I can't spin up an ec2 instance using the marketplace image per my account permissions. I can copy an AMI and spin up an instance using the copied AMI. We would also look into automating the creation of the images using something like packer. If you're able to make the AMIs (listed on rocky linux's website) completely public, that'd be awesome

![rocky-ami2](https://user-images.githubusercontent.com/60984725/169908159-ff18c675-4a47-4f7e-a935-853536e92f5b.png)
![rocky-ami1](https://user-images.githubusercontent.com/60984725/169908160-789944b0-601f-40fe-a260-ca33dffe32ee.png)

**Comment by NeilHanlon** [comment]
> @boegel @NeilHanlon for reference, this is effectively what happens when I try to copy an AMI. I can't spin up an ec2 instance using the marketplace image per my account permissions. I can copy an AMI and spin up an instance using the copied AMI. We would also look into automating the creation of the images using something like packer. If you're able to make the AMIs (listed on rocky linux's website) completely public, that'd be awesome

Thanks for the report! I am looking into this, hopefully have an answer soon. I'm also working on getting the marketplace images published..running into some publishing issues there.

**Comment by cynicaljoy** [comment]
Leaving a note here as it wasn't obvious to me why this was closed, hope it helps somebody else.

If you use the AMIs from the Marketplace you'll be unable to produce an AMI and copy it to other AWS Accounts:

```
An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.
```

However, if you use the AMIs from https://rockylinux.org/cloud-images/ you'll be able to produce AMIs that can be copied.

**Comment by NeilHanlon** [comment]
> Leaving a note here as it wasn't obvious to me why this was closed, hope it helps somebody else.
> 
> If you use the AMIs from the Marketplace you'll be unable to produce an AMI and copy it to other AWS Accounts:
> 
> ```
> An error occurred (InvalidRequest) when calling the CopyImage operation: Images from AWS Marketplace cannot be copied to another AWS account.
> ```
> 
> However, if you use the AMIs from https://rockylinux.org/cloud-images/ you'll be able to produce AMIs that can be copied.

Heya - Sorry that this was left alone for so long. That's my bad.

You're correct that you cannot just copy the marketplace AMI to another account, and must use the image IDs we offer on the site. These are the same AMIs, fwiw, but AWS requires you 'Subscribe' to the marketplace image, which is, in essence, copying the image from the AWS-owned account to your own.

In any case, it sounds like you've figured it out but, you can access the raw data for the cloud-images page [here](https://github.com/rocky-linux/rockylinux.org/blob/main/src/data/cloud-images.json), in case you wanted to programmatically find the right AMI. Our web team (@rocky-linux/web-leads) has also been working on a first-class API for this data in our new website.

Best,
Neil

**Comment by cynicaljoy** [comment]
Being able to lookup the AMI IDs from an API sounds _awesome_. It would also be cool if there was a public AWS SSM Parameter Store that had the latest AMI ID. Is there an open issue for this somewhere that I could follow?

**Comment by NeilHanlon** [comment]
You're not the first person who has asked for this (SSM Parameter Store), but when I last looked, I could not find any documentation on how to actually do this. From what I could tell, it is something that AWS manages and we don't actually have control over. Again, that was from what I could tell. If you have any documentation on that, I'd be happy to take a look

**Comment by cynicaljoy** [comment]
Ah yeah, it looks like only AWS has the ability to create generally public SSM params 😢  -- API sounds great, but the JSON file is totally usable in the meantime. Thank you!

**Comment by ziggythehamster** [comment]
>  I could not find any documentation on how to actually do this. From what I could tell, it is something that AWS manages and we don't actually have control over.

Do y'all have an AWS Technical Account Manager? They should be able to get you set up with the right folks. If you don't have a TAM, I can probably ping someone in the open source group to reach out. (Assuming they're still onboarding external customers, but I don't see any evidence they're not doing that.)

From what I can tell (not working at AWS, but rather an Amazon subsidiary), you should have the ability to update parameters without AWS intervention, but I don't know whether that extends to new parameters or not.
