### ISSUE TITLE
Rocky Amazon Machine Image fails to output host keys on boot

### ISSUE THREAD

**Issue by mikedlr** [rocky-linux/rockylinux.org-gatsby#198]
## To Reproduce

1. start an EC2 instance in AWS
2. wait for complete boot and then some (it takes time for log to arrive)
3. instances -> select appropriate instance checkbox -> Actions -> Monitor and troubleshoot -> Get system log
4. Look at end of log

## Actualbehavior

empty fingerprint list is output like so:

```
<14>Sep  3 22:47:39 ec2: #############################################################
<14>Sep  3 22:47:39 ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----
<14>Sep  3 22:47:39 ec2: -----END SSH HOST KEY FINGERPRINTS-----
<14>Sep  3 22:47:39 ec2: #############################################################
-----BEGIN SSH HOST KEY KEYS-----
-----END SSH HOST KEY KEYS-----
```
also login prompt is displayed on console - I don't think it should be.

## Expected behavior

The complete list of host keys should be output as with other AMIs

## Device Information

**Desktop (please complete the following information):**

- OS:  Rocky Linux 8
- Region: us-east-2
- Instance type: t2.micro
- AMI name: Rocky Linux 8.4-d6577ceb-8ea8-4e0e-84c6-f098fc302e82
- AMI location: aws-marketplace/Rocky Linux 8.4-d6577ceb-8ea8-4e0e-84c6-f098fc302e82

**Comment by rlhennig** [comment]
This is not the appropriate place for reporting this kind of bug, as this repo is more for the website. I would create a bug here https://bugs.rockylinux.org/ and then as well see if the same behavior is seen on Centos.
