### ISSUE TITLE
Create Partners Page

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#20]
We differentiate between donors, sponsors, and partners. Briefly:

**Donors** are for individuals who want to send one-offs or smaller sums

**Sponsors** are for organizations that want to provide more significant financial backing

**Partners** are for organizations that provide more strategic value, which may not equate to direct financial support. Mattermost is an example. 

Because we differentiate between these, we want to have a separate page dedicated toward partners. I'm not sure how this might look visually, but at least to start we could model it off of the current sponsors page, perhaps? Given that I have almost zero design ability or intuition, I'll leave that up to you!

One thing we do want to include on the partners page though is a section dedicated to those folks who are hosting mirrors for us. We want to make sure we're thanking them. 

Thank you!

**Comment by FoggyMtnDrifter** [comment]
I can start working out a rough draft on this later today. I'll post updates here just to keep things a little more organized.

**Comment by FoggyMtnDrifter** [comment]
Do we have a list available for all current partners? I'm playing around with ideas and would like a list that might be able to give me a better idea of how to lay out the page.

**Comment by rlhennig** [comment]
CIQ would actually be a partner. So would Naver.

**Comment by FoggyMtnDrifter** [comment]
Okay, so should CIQ and Mattermost be moved to the partners page and removed from sponsors @rlhennig?
