### ISSUE TITLE
Add Supermicro to Partners Page

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [rocky-linux/rockylinux.org-gatsby#201]
We need to add Supermicro to the Partners Page with the following text blurb:
**As a global leader in high performance, high-efficiency server technology, and innovation Supermicro is excited to work with the RESF and deliver data center servers and storage systems optimized for Rocky Linux.**

[SupermicroLogo.zip](https://github.com/rocky-linux/rockylinux.org/files/7307431/SupermicroLogo.zip)

**Comment by hbjydev** [comment]
@ressonix Are you gonna do this one or should I throw a PR?
