### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by spirillen** [rocky-linux/rockylinux.org-gatsby#203]
## Describe the bug

Your website `https://rockylinux.org/`) isn't working and you have troubles with the SSL cert

```
Secure Connection Failed

An error occurred during a connection to rockylinux.org. PR_END_OF_FILE_ERROR
```

## To Reproduce

Open your Tor browser try to connect in private to `https://rockylinux.org/` 

## Expected behavior

A webpage showing your a financed by google spyware

## Screenshots

![image](https://user-images.githubusercontent.com/44526987/137016989-42dacb20-ac5a-4372-b8d0-4a2e9eccfb22.png)

## Device Information

**Desktop (please complete the following information):**

- OS: [e.g. iOS] 5.14.2-051402-generic
- Browser [e.g. chrome, safari] Tor for better privacy
- Version [e.g. 22] 10.5.8 (based on Mozilla Firefox 78.15.0esr) (64-bit)

**Additional context (Please delete this if there's no additional context):**

**Comment by NeilHanlon** [comment]
Hi,

I am unable to replicate this, and further am not sure what you are referencing with respect to the 'google spyware'.

To my knowledge, we have not had an outage on our site. If you are still encountering this trouble please let us know.
