### ISSUE TITLE
Add Page for Keys of Rocky Linux & Team members

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/rockylinux.org-gatsby#205]
**Is your feature request related to a problem? Please describe.**

We would like to add a new page that details and mostly mirrors https://centos.org/keys/ but for our downstream
project. Essentially, a place to store the fingerprints and download links for the signing, debug, and testing keys for
each major version of Rocky, any SIGs, and whatever future use may exist. Possibly including Security/Infrastructure
team Keys and/or information regarding Keybase as a contact method for security vulnerabilities.

**Describe the solution you'd like**

Add some copy and (at least) the keys from https://dl.rockylinux.org/pub/rocky/ .

For Rocky Linux 8 Project Keys, these are the fingerprints, exported from my keyring.

### Rocky Linux Official Key

```
pub   rsa4096/0x15AF5DAC6D745A60 2021-02-14 Rocky Linux (Rocky Linux Official Signing Key) <releng@rockylinux.org>
      Key Fingerprint = 7051 C470 A929 F454 CEBE 37B7 15AF 5DAC 6D74 5A60
```

### Rocky Linux Testing Key

```
pub   rsa4096/0x5489E42BBBE2C108 2021-02-14 Rocky Linux Testing (Rocky Linux Testing Key) <releng@rockylinux.org>
      Key fingerprint = 091A 4404 7C3D 8B7A 331F  5E18 5489 E42B BBE2 C108
```

### Rocky Linux Infrastructure Key
```
sec   ed25519/0xAA650F52D6C094FA 2021-05-17 Core Infrastructure (Compose Signing Key) <infrastructure@rockylinux.org>
      Key fingerprint = BFC3 D8F2 0D15 F4FD 4628  1D7F AA65 0F52 D6C0 94FA
```

**Describe alternatives you've considered**

N/A

**Additional context**

Had been brought up before in the community, and more recently an email to the contact address requesting it!

**Comment by NebraskaCoder** [comment]
I can take a look at this.

**Comment by FoggyMtnDrifter** [comment]
Hey there, @NebraskaCoder! Were you able to work on this? :)

**Comment by NebraskaCoder** [comment]
Hey, @ressonix! The page is built, but I will need someone to verify the current text and provide the keys. Also, spot-checking the GPG command, as the one on the CentOS page doesn't work anymore. I will start a pull request so that the page can be reviewed.

**Comment by NebraskaCoder** [comment]
Hey, @ressonix! The page is built, but I will need someone to verify the current text. Also, spot-checking the GPG command, as the one on the CentOS page doesn't work anymore. I will start a pull request so that the page can be reviewed.

@NeilHanlon - What command did you use to get the fingerprints as the one on the CentOS page doesn't actually print the keys.

**Comment by NebraskaCoder** [comment]
Please take a look at my PR #219 using the Vercel link and going to /keys (https://rockylinux-opunkdh5e-resforg.vercel.app/keys/)

**Comment by NeilHanlon** [comment]
> @NeilHanlon - What command did you use to get the fingerprints as the one on the CentOS page doesn't actually print the keys.

```
[root@24710dfdaad9 /]# gpg --keyid-format 0xlong --show-keys <(curl -s https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-rockyofficial) 2>/dev/null
pub   rsa4096/0x15AF5DAC6D745A60 2021-02-14 [SCE]
      7051C470A929F454CEBE37B715AF5DAC6D745A60
uid                              Release Engineering <infrastructure@rockylinux.org>
```

Is one way!

**Comment by NeilHanlon** [comment]
Hm, actually looks like the command CentOS references works on my machine as well:

```
╰─ gpg --quiet --with-fingerprint ~/Downloads/RPM-GPG-KEY-rockyofficial
pub   rsa4096/0x15AF5DAC6D745A60 2021-02-14 [SCE]
      Key fingerprint = 7051 C470 A929 F454 CEBE  37B7 15AF 5DAC 6D74 5A60
```

**Comment by NebraskaCoder** [comment]
I'm not sure why but when I run the command, I don't get the Key fingerprint. Which command do you want on the page? Also, where do you want the link to the keys page? Anything you want me to change on the page as well before taking the PR out of draft mode (https://rockylinux-opunkdh5e-resforg.vercel.app/keys/)?

**Comment by NeilHanlon** [comment]
The `--with-fingerprint` should print the 'Key fingerprint` information. Lets use that one in the section here 

![image](https://user-images.githubusercontent.com/680198/142335536-c767e183-0a82-4a00-9ff5-612b6c7cdba4.png)

Below, where you display the keys, that looks great. The format is a little weird and might change in the future so that it is just the output of a command. One the page is up there we can play around with it! 

Regarding where it should be linked to from: I have no strong preference. It seems it belongs somewhere under security, probably. We'll likely link into it from elsewhere, as well.

@ressonix & @brianclemens any ideas?

**Comment by NebraskaCoder** [comment]
The `gpg --quiet --show-keys /etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial` worked for me. I'll update it now.

**Comment by NebraskaCoder** [comment]
Disregard. That command is the one I already have. I'll wait to hear from @ressonix and @brianclemens for ideas.

**Comment by NeilHanlon** [comment]
Ah, it looks like `--show-fingerprints` was added in a newer version of gnupg, which probably explains what's going on. Let's leave it with this command, it's essentially just some reformatting around it.

```
╭─<neil@afterman-ascension>-<~/Downloads>-<9:43PM>-◇
╰─ gpg --quiet --show-key RPM-GPG-KEY-rockyofficial                                                                                                            130 ↵
pub   rsa4096/6D745A60 2021-02-14 [SCE]
      7051C470A929F454CEBE37B715AF5DAC6D745A60
uid                    Release Engineering <infrastructure@rockylinux.org>

```

**Comment by brianclemens** [comment]
On a related note, I've made the keys discoverable via WKD with f8f8594621d9371c6859e1ad8421d25df7e10370

This doesn't address the primary issue here (a human readable page), but the import instructions on the page should likely be updated to use import via WKD.

**Comment by FoggyMtnDrifter** [comment]
@NebraskaCoder If you've got everything suggested by @NeilHanlon here, it looks great to me! I'm leaving it to others on what the content should look like, but the page itself looks great!

**Comment by NebraskaCoder** [comment]
@ressonix The outstanding question I had was where we wanted to link to this page at.

**Comment by FoggyMtnDrifter** [comment]
I see! Sorry for the confusion, I have been out this week and haven't had much of a chance to catch up. 

Let's place it next to the AMI List link on the Downloads page.

**Comment by NebraskaCoder** [comment]
Will do. Thanks!
