### ISSUE TITLE
Update site w/ 45Drives Sponsorship Info

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#22]
We recently signed an agreement with 45Drives for a Principal Sponsorship. Can you please help with the following?

1. Add their logo to the Sponsors page
2. Add supplied text summary next to logo 
3. Add logo to rotating on main landing page

The logo should click through to their website: https://www.45drives.com/

Here's a link to the logo they'd like us to use: https://web.tresorit.com/l/Vtmpn#BeLAnitnXpbZPtVNCd57RA

Text:

> 45Drives offers an enterprise storage solution built on powerful and robust open-source software that allows customers to benefit from the cost savings and flexibility of off-the-shelf hardware. Our company provides a software agnostic, fully supported data storage solution at the best cost per terabyte.
 
> Since 45Drives solutions are built on open-source software, this eliminates high licensing fees and increases innovation inherent to the open-source development model. With a 45Drives’ solution, the challenges of traditional do-it-yourself open-source deployments are solved by having a team of expert support staff.
45Drives has sold to some of the world’s largest organizations. Organizations, including top leading universities, Bloomberg, Google, and NASA all rely on the integrity of 45Drives solutions to store their data.

Thank you!

**Comment by FoggyMtnDrifter** [comment]
So I know in the Community Update the Principal Sponsor is supposed to get 180 characters for the text under their logo. This description is a bit long. Do we have a short version that meets the character limit?

**Comment by FoggyMtnDrifter** [comment]
Also, can I get a list of all sponsors and their Tier level? I know OpenDrives is also a Principal Sponsor (and I believe CtrlIQ), but I just want to make sure we have everything we need to make sure we'll following the things we set out in the Community Update.

**Comment by FoggyMtnDrifter** [comment]
Here's the general layout I've worked up for the sponsors page. We have the description under the logo, with the logo and company name being clickable. 

![image](https://user-images.githubusercontent.com/60057409/109428117-90cefd00-79c3-11eb-9786-006e3711f631.png)

**Comment by rlhennig** [comment]
Would it be possible to have only part of the description visible beneath or beside the logo, with an ellipsis trailing off to indicate there's more? And then perhaps if you click on the logo, it expands in the webpage to the full description? Then perhaps if you click again it folds it back into place, or if you click another sponsor their longer description unfolds? Not sure if that makes sense or is even possible

**Comment by hbjydev** [comment]
The description should probably be shorter anyway tbh, I don't want to do folding descriptions because it relies on client-side JavaScript and people seem to be opposed to that.

**Comment by hbjydev** [comment]
Or is this something 45Drives have requested to have on the site? @rlhennig

**Comment by rlhennig** [comment]
No, not something they requested on their site. This is what would show up on theirs. I will go back to them and ask for a shorter description--our contract states 180 *characters* so that should be what we'll need to add at a minimum. The idea was to have it be the length of a tweet, which I believe is now 280 c Can you think of any other ways that we can include something longer?

**Comment by hbjydev** [comment]
I don't think we *should* generally, 180c sounds fine to me length-wise.

**Comment by rlhennig** [comment]
Let's stick to 280 chars then, because that's what fits within a tweet. Here's what 45Drives updated us with:

> 45Drives offers enterprise storage solutions built on powerful & robust open-source software that allows customers to benefit from the cost savings & flexibility of off-the-shelf hardware. Check them out for a fully supported data storage solution at the best cost per terabyte!

Can we use that please?

**Comment by rlhennig** [comment]
In order to have two side-by-side, can we please put CIQ next to 45Drives for now? We can use the following quote for CIQ:

> Unified, secured, platform agnostic computing starting with the provisioning, management, and support of the base OS (Rocky Linux) and going through the deployment stack of containers with cloud native, multi-prem, multi-cloud meta-orchestration of performance critical workflows and data.

**Comment by rlhennig** [comment]
You asked for a transparent logo for 45Drives, here's what they sent me: https://web.tresorit.com/l/JdhCc#BsbTUkRwiIN9aiz1BrO2WQ

Will this work?
