### ISSUE TITLE
arm install doesnt start on mac m1

### ISSUE THREAD

**Issue by it-pappa** [rocky-linux/rockylinux.org-gatsby#234]
## Describe the bug

Trying to install Rocky on ARM thru vmware fusion (beta). See the first menu but when choosing Install or test it will just refresh. 

## To Reproduce

Vmware Fusion on Mac m1, and Rocky ARM.

**Comment by it-pappa** [comment]
wrong repo

**Comment by adleader** [comment]
The computer with Apple silicon chip needs to set the kernel pagesize to 16k or 4k. I have no way to compile the kernel. On centos7, I have completed the pagesize of 16k or 4k.
