### ISSUE TITLE
Update AMI IDs for 8.5

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/rockylinux.org-gatsby#235]
New AMI Ids and regions

### aarch64
```
eu-north-1,ami-09c237aa6f84aa31d
ap-south-1,ami-0f9e8f0b3490c929c
eu-west-3,ami-0cb170992520649fa
eu-west-2,ami-0f626368bef526180
eu-west-1,ami-05bdfaac44dd4f8be
ap-northeast-3,ami-052198efa1a75e212
ap-northeast-2,ami-08ae751f8a19fb9b5
ap-northeast-1,ami-084d423cf7accd8d9
sa-east-1,ami-06674197fb810dc0c
ca-central-1,ami-033e74798225e42e4
ap-southeast-1,ami-064be01ca69cd982d
ap-southeast-2,ami-0171b2fa317eb0d6d
eu-central-1,ami-0a9cd4ee47ff73e1d
us-east-1,ami-096e199c58bb0653f
us-east-2,ami-0b6159d240ab78b1a
us-west-1,ami-0b5ea38a0532d8a30
us-west-2,ami-08eb90c0d94c32ff4
```

### x86_64
```
eu-north-1,ami-0090b17f0ffd314ba
ap-south-1,ami-099589c84ecec2f81
eu-west-3,ami-0abb90b1685f9e9fc
eu-west-2,ami-0768c1f18418e882d
eu-west-1,ami-0a10fe11f3e1bf41e
ap-northeast-3,ami-0ce722d42255297b9
ap-northeast-2,ami-0280ce8ecafa32cf7
ap-northeast-1,ami-0ddb05e945a674cf5
sa-east-1,ami-07177719c7d6b0ac4
ca-central-1,ami-09ada793eea1559e6
ap-southeast-1,ami-0514af8e1e699170c
ap-southeast-2,ami-01d801fcba2e682d0
eu-central-1,ami-079f4c25253b27e9d
us-east-1,ami-043ceee68871e0bb5
us-east-2,ami-08882eba49067074f
us-west-1,ami-0335e1660e1197d63
us-west-2,ami-09ca837d91f083d04
```

**Comment by stephen-dexda** [comment]
None of these seem to match the AMI IDs on the AWS marketplace for the 20211114 versions. For instance, the x86_64 us-east-1 AMI ID per https://aws.amazon.com/marketplace/server/configuration?productId=d6577ceb-8ea8-4e0e-84c6-f098fc302e82 (login required), via https://aws.amazon.com/marketplace/pp/prodview-2otariyxb3mqu, is ami-0ec1545979d0dc885, not ami-043ceee68871e0bb5.

In contrast, the us-east-1 AMI ID for the 2021-06-21 version from the above page is ami-02628ddf3745c6dda, which *does* match the ID published at https://rockylinux.org/ami.

All this said, the AWS marketplace is an absolute disaster, so please tell me if there's a reason I'm completely wrong about this.

**Comment by stephen-dexda** [comment]
The [aarch64 Rocky product on the marketplace](https://aws.amazon.com/marketplace/pp/prodview-uzg6o44ep3ugw) doesn't have an 8.5 version at all, but for the [8.5 x86_64 product](https://aws.amazon.com/marketplace/pp/prodview-2otariyxb3mqu), these are the IDs I see (AWS' API is so crap that it doesn't let me specify any of "seller", "product" or "version", despite all of those existing on their web interface :J):

```bash
$ for region in \
  ap-northeast-1 \
  ap-northeast-2 \
  ap-northeast-3 \
  ap-south-1 \
  ap-southeast-1 \
  ap-southeast-2 \
  ca-central-1 \
  eu-central-1 \
  eu-north-1 \
  eu-west-1 \
  eu-west-2 \
  eu-west-3 \
  sa-east-1 \
  us-east-1 \
  us-east-2 \
  us-west-1 \
  us-west-2 \
; do
  printf '%-15s' "$region"
  aws --region="$region" ec2 describe-images \
    --filters \
      Name=root-device-type,Values=ebs \
      Name=product-code,Values=cotnnspjrsi38lfn8qo4ibnnm \
      Name=description,Values='*20211114*' \
      Name=architecture,Values="$arch" \
  | yq -re '.Images[].ImageId'
done

ap-northeast-1 ami-01c6603b0b5d545ec
ap-northeast-2 ami-0bd5ab4cea306d466
ap-northeast-3 ami-0f436e9347fdef51a
ap-south-1     ami-0a37881658d1d7ccd
ap-southeast-1 ami-070374e718db7f3bf
ap-southeast-2 ami-0b07acd3d4aebc454
ca-central-1   ami-0f9407f98ce39bf1f
eu-central-1   ami-05b44291810dff0b2
eu-north-1     ami-03ab37ade73ce076e
eu-west-1      ami-071dac00197ca7d33
eu-west-2      ami-03d16bcad5b0973f3
eu-west-3      ami-06ff90786c0091ac8
sa-east-1      ami-02eb71c57310bb7ff
us-east-1      ami-0ec1545979d0dc885
us-east-2      ami-0c2c9b5652599cf35
us-west-1      ami-0ebd02eb2199a3c8d
us-west-2      ami-089a307da2bb2c8a3
```

**Comment by NeilHanlon** [comment]
Hey -

Yes, that's correct on both parts.

Aarch64 for 8.5 on the marketplace is awaiting an internal ticket with AWS regarding publishing.

These AMI IDs are not the marketplace AMIs, but ones from our account which is used to publish said AMIs to the marketplace. This has been requested by several people versus the AMIs for the marketplace images, as the marketplace images require subscription, which can be a bit of a pain with automation (e.g. with terraform).

We're happy to provide both options if that's preferable, but rest assured they'll be the same images, just from different accounts! The account ID which will share our AMIs is 792107900819. You should see matching AMIs for both x86_64 and aarch64 published in all regions from this account.

**Comment by stephen-dexda** [comment]
Ah OK, that is actually very useful for another reason too - it makes it possible to find Rocky images matching criteria (without using fixed AMI IDs) and guarantee, using the Rocky acc. ID, that only ones published by Rocky are returned (which seems to be impossible on the marketplace via the AWS API).

Maybe the above acc. ID should be published on the Rocky AMI page as well, for this reason?

**Comment by NeilHanlon** [comment]
Definitely! I'm going to update this to include a request to add that info
as well as our Product ID(s) in the marketplace.

A little writeup on this is on the way
