### ISSUE TITLE
Add community calendar

### ISSUE THREAD

**Issue by brianclemens** [rocky-linux/rockylinux.org-gatsby#236]
The community events calendar (public team meetings, release parties, etc) should be shown somewhere on the website. There are a few Gatsby calendars available that use either the iCal feed or the Google API, so I've listed both here:

|Type | Link
| --- | ---
|iCal | https://calendar.google.com/calendar/ical/c_2e1oqh6t0i6sqhja5nu9lq8lgo%40group.calendar.google.com/public/basic.ics |
|Google calendar ID | c_2e1oqh6t0i6sqhja5nu9lq8lgo@group.calendar.google.com
|Google calendar sharing link | https://calendar.google.com/calendar/u/0?cid=Y18yZTFvcWg2dDBpNnNxaGphNW51OWxxOGxnb0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by FoggyMtnDrifter** [comment]
After some deliberation, I'm going to have to go with the simplest route in this case, which is just linking to the public calendar itself from the footer. While we could use one of the plugins available for Gatsby, every time an event is added (or cancelled), it would require a complete site re-build, which wouldn't be efficient in the long-term. It is much more efficient to link to the public calendar itself. If another solution comes up at some point, I'm all ears, but the current solutions aren't that great.
