### ISSUE TITLE
Languages Don't Parse When Using Switcher

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [rocky-linux/rockylinux.org-gatsby#25]
## Describe the bug

When using the language switcher (with JavaScript enabled), the languages don't get parsed. Oddly enough, if you refresh the browser after switching from the switcher, the language parses. It seems something is causing it not to parse after the onClick event.

## To Reproduce

1. Make sure JavaScript is enabled in your browser.
2. Choose a language (other than English) in the switcher in the footer of the site.

## Expected behavior

The language should be parsed when using the switcher with JavaScript enabled.

## Screenshots

![image](https://user-images.githubusercontent.com/60057409/109605014-7b0c2580-7af2-11eb-87ad-3de7e34f4c4e.png)

**Comment by FoggyMtnDrifter** [comment]
@hbjydev Can you take a look at this? I've done some work and pushed some changes in the `develop` branch with no luck. The switcher works properly when running the dev server locally, so the issue only occurs after build. I originally thought it might have been something to do with RSS because of some console errors but I completely removed it and the issue still persisted. I don't have the best knowledge when it comes to the i18n stuff and I'm not seeing anything extremely apparent that would be causing such an issue.

**Comment by mstg** [comment]
I've taken a look and it seems to be that only the current locale is loaded at any given time. This happens because of the `load: 'currentOnly'` in `gatsby-config.js`. I see two ways that this can be fixed.

Either load all locales at all times:
```patch
diff --git a/gatsby-config.js b/gatsby-config.js
index f97d085..6bcd3f9 100644
--- a/gatsby-config.js
+++ b/gatsby-config.js
@@ -111,7 +111,7 @@ module.exports = {
           ],
           fallbackLng: 'en',
           lowerCaseLng: 'true',
-          load: 'currentOnly',
+          load: 'all',
           ns: ['translation'],
           returnObjects: true,
           interpolation: {
```

or instead of doing a client-side navigate, do a full page reload on locale change:
```patch
diff --git a/src/components/footer/index.jsx b/src/components/footer/index.jsx
index df7f43d..c34b750 100644
--- a/src/components/footer/index.jsx
+++ b/src/components/footer/index.jsx
@@ -163,11 +163,11 @@ const Footer = ({ pageContext: { locale: language } }) => {
             </h5>
             <select
               id="languagePicker"
-              onChange={(e) =>
-                navigate(
-                  `${e.target.value === 'en' ? `/` : `/${e.target.value}`}`
-                )
-              }
+              onChange={(e) => {
+                window.location.href = `${
+                  e.target.value === 'en' ? `/` : `/${e.target.value}`
+                }`;
+              }}
               name="language"
               className="mt-1 mr-2 block w-full pl-2 pr-8 py-1 text-sm text-black dark:text-white border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm rounded-md"
               aria-label="Language Select"
```

I think option 2 is more favorable but that is for you all to decide

**Comment by hbjydev** [comment]
Full page reload is definitely the favorable option. I'm using Lighthouse audits as a performance benchmark and we will take a _big_ hit on load times if we do the `load: 'all'` version.

Can you open a PR for this @mstg?

**Comment by hbjydev** [comment]
That way we get a Vercel preview build we can test it with

**Comment by mstg** [comment]
@hbjydev I am also definitely in favor of performance and therefore option 2. Opened #26
