### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by lokalisoija** [rocky-linux/rockylinux.org-gatsby#316]
Add dark mode to the website.

**Comment by iprasandeep** [comment]
@ressonix I would like to work on this issue, thanks:)

**Comment by FoggyMtnDrifter** [comment]
@prsndp Still interested in working on this?

**Comment by thijsvanderwoude** [comment]
@ressonix I am definitely interested!

**Comment by FoggyMtnDrifter** [comment]
Great @thijsvanderwoude! I'll assign the issue to you. Feel free to make a PR when you've completed it. 😄

**Comment by thijsvanderwoude** [comment]
@ressonix I got the site running locally. Is there a style guide that I haven't been able to find or should I put on my front-ender hat?

**Comment by FoggyMtnDrifter** [comment]
TailwindCSS has support for dark mode built in, it's just a matter of adding the appropriate classes. See: https://tailwindcss.com/docs/dark-mode

TailwindCSS will automatically use the visitor's OS color scheme preference. So, for instance, if you have dark mode set on Windows, the website will load in dark mode.

For a color palette, see: https://tailwindcss.com/docs/customizing-colors#default-color-palette

We would prefer you use the 'gray' palette. Just make sure things are legible and have decent contrast and it should be fine.
