### ISSUE TITLE
Translation Completed: Italian

### ISSUE THREAD

**Issue by sgob1** [rocky-linux/rockylinux.org-gatsby#317]
**Language Translated:** Italian

**Localized Language Name:** Italiano

**ISO 639-1 Language Code:** `it`

**Localized Date Format:** `DD/MM/YYYY`

---
Hope this helps out
Merry Christmas

**Comment by ressonix** [comment]
Let's add @sgob1 for translation @all-contributors

**Comment by FoggyMtnDrifter** [comment]
@all-contributors please add @sgob1 for translation
