### ISSUE TITLE
Creation of Company-Account only possible in US

### ISSUE THREAD

**Issue by SiJux** [rocky-linux/rockylinux.org-gatsby#324]
Hello Rocky Team,

we would like to donate as company. 
Unfortunately it isn't possible to create a company-account outside the US:
https://donate.rockylinux.org/np/clients/rockylinux/donation.jsp?forwardedFromSecureDomain=1&constTypeFlag=org

As Individual it's possible to select a country:
https://donate.rockylinux.org/np/clients/rockylinux/donation.jsp?forwardedFromSecureDomain=1&forwardedFromSecureDomain=1

Is it intended that way? 

Thanks for checking.

Regards
Simon

**Comment by FoggyMtnDrifter** [comment]
Hey there! Please shoot an email to hello@rockylinux.org and a member of our leadership team will follow up with you regarding this. 😁
