### ISSUE TITLE
Update copyright year automatically?

### ISSUE THREAD

**Issue by lstefan1520** [rocky-linux/rockylinux.org-gatsby#327]
#### Description

Copyright year is outdated on the site, it's defined within each translation. Perhaps using a built-in function get the copyright year instead of defining it within each translation file. This may perhaps require updates to crowdin? Unless it does it updates automatically....

#### Files

footer.js

#### To Reproduce

Check footer

**Comment by iprasandeep** [comment]
@ressonix  Hi, If no one is working on this issue then I would like to work on this ticket. Thanks:)
