### ISSUE TITLE
Translation Completed: Chinese Simplified

### ISSUE THREAD

**Issue by jimcat8** [rocky-linux/rockylinux.org-gatsby#329]
**Language Translated:** Chinese Simplified

**Localized Language Name:** Chinese Simplified

**ISO 639-1 Language Code:** `zh_cn`

**Localized Date Format:** e.g. `YYYY/MM/DD`

**Comment by FoggyMtnDrifter** [comment]
@all-contributors please add @jimcat8 for translation
