### ISSUE TITLE
Fix the multiple broken URLs used on the cloud-images page

### ISSUE THREAD

**Issue by quadespresso** [rocky-linux/rockylinux.org-gatsby#332]
#### Description

When visiting this page:

https://rockylinux.org/cloud-images

and clicking on any valid **Deploy** link other than the ones for `us-west-1`, the AWS console pops up a message such as this:

> We cannot proceed with your requested configuration. This AMI (ami-09ca837d91f083d04) does not exist.
The specified AMI you are trying to use has an invalid ID, does not exist, or does not exist in this region. Check the AMI details, or try again with a valid AMI.

One link in particular also has a trumcated AMI ID; `ap-northeast-2` lists `ami-0280ce8ecafa32cf` instead of `ami-0280ce8ecafa32cf7`.

#### Screenshots

The screenshot matching the quoted passage above:

![image](https://user-images.githubusercontent.com/6423333/150238177-661b1ddd-1c99-4f77-8d1f-55c211b853c8.png)

All of the other broken links (and in particular, the AMI ID used for `ap-northeast-2`) will result in the same failure (with the AMI ID changed as appropriate).

#### Files

https://github.com/rocky-linux/rockylinux.org/blob/develop/src/pages/cloud-images.js

or the latest commit (as of this writing):

https://github.com/rocky-linux/rockylinux.org/blob/7c9d46556f0586c05b5c90bbc55261dd8d527c99/src/pages/cloud-images.js

#### To Reproduce

1. Visit: https://rockylinux.org/cloud-images
1. Select any region _other than_ `us-west-1`
1. Click the **Deploy** link

**Comment by quadespresso** [comment]
I have a change staged locally. Ready to create a PR at any time.

I've vetted all of the changed links, and they all appear to work now.

**Comment by FoggyMtnDrifter** [comment]
Hey there, @quadespresso! Thanks for bringing this to our attention! Feel free to go ahead and make the PR. :))

**Comment by quadespresso** [comment]
@ressonix PTAL #338
