### ISSUE TITLE
Two different names for the Rocky Foundation in February News?

### ISSUE THREAD

**Issue by AtjonTV** [rocky-linux/rockylinux.org-gatsby#34]
## Describe the bug

On the February News article in the first paragraph near the end it says the name changed to `Rocky Software Enterprise Foundation` yet under Legal it says `Rocky Enterprise Software Foundation`.

It's a fairly minor issue but will cause confusion when reading and not knowing which is correct.

**Comment by jorp** [comment]
fixed per https://github.com/rocky-linux/rockylinux.org/pull/38. great eye @AtjonTV, thank you!

**Comment by AtjonTV** [comment]
Thanks, but what about the things I actually mentioned? That in Summery and Legal there are two different ways the new name is written ..

`The Linux Foundation to license Rocky Linux under the Rocky Software Enterprise Foundation,`

Note the "Rocky Software Enterprise"

`We have renamed the “Rocky Linux Foundation” (RESF) to the “Rocky Enterprise Software Foundation”`

Note the "Rocky Enterprise Software"

**Comment by jorp** [comment]
@AtjonTV Forgive me for not reading that thoroughly.. I have now addressed this  [here](https://github.com/rocky-linux/rockylinux.org/pull/38/commits/0671bc70f0c990acc7e9def9224f0f59ef23da4b). I'm glad that enabled me to find another inconsistency, so thank you x2.
