### ISSUE TITLE
Create high level "Legal" page that links to important documents, etc

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/rockylinux.org-gatsby#359]
From rocky-linux/sig-cloud-instance-images#5

**Comment by amithbs1** [comment]
@ressonix I would like to take up this issue, if nobody is working on it. I've got the project working on my local and added the high level "Legal" page, might need help with the content.
![image](https://user-images.githubusercontent.com/47681946/167263160-02f364de-62da-4d8e-9701-06c94e7fd4ac.png)

**Comment by FoggyMtnDrifter** [comment]
Hey there, @amithbs1! This looks great! The verbiage seems fine to me. If you want to go ahead and create a PR and link this issue, I'll review and merge!

**Comment by amithbs1** [comment]
@ressonix Thanks for the quick response. I am trying to raise a PR but it seems like I don't permission to the remote repo. 
![image](https://user-images.githubusercontent.com/47681946/167265914-bb78e6cf-2649-46fc-b135-a14016a57e95.png)
Sorry if I am missing something. I have run all the pre-commit checks, but unable to push the code to the remote repository.

**Comment by FoggyMtnDrifter** [comment]
Hey @amithbs1! You need to fork the repo, push the code to your fork, then make a Pull Request here for your fork.

See: https://opensource.com/article/19/7/create-pull-request-github

**Comment by amithbs1** [comment]
> Hey @amithbs1! You need to fork the repo, push the code to your fork, then make a Pull Request here for your fork.
> 
> See: https://opensource.com/article/19/7/create-pull-request-github

@ressonix Sorry I deleted my comment before you could respond. Thanks for pointing me to the right direction.
I have now raised a PR for your review (#388), kindly let me know if more changes are required.
Thanks,
Amith Sai

**Comment by FoggyMtnDrifter** [comment]
@all-contributors please add @amithbs1 for content
