### ISSUE TITLE
Support security.txt RFC9116

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/rockylinux.org-gatsby#366]
#### Description

We should consider supporting this new proposed standard.

https://www.rfc-editor.org/rfc/rfc9116

We should also make sure we have a security policy written up and published, etc, to link to.

ex: 
```
Contact: mailto:security@rockylinux.org
Expires: 2022-12-31T17:59:00.000Z
Encryption: https://rockylinux.org/some/path/here
Canonical: https://rockylinux.org/.well-known/security.txt
```

**Comment by brianclemens** [comment]
Added in ba5d682
