### ISSUE TITLE
Incorrect text for Traditional Chinese on language selector

### ISSUE THREAD

**Issue by toto6038** [rocky-linux/rockylinux.org-gatsby#391]
#### Description

Traditional Chinese is referred to as 正體中文 or 繁體中文, and the current text is neither of them.

#### Screenshots

![圖片](https://user-images.githubusercontent.com/50100922/167269171-0db9f461-5a75-469b-b586-e400ddcaa657.png)

**Comment by FoggyMtnDrifter** [comment]
Thanks for the report! I've merged your PR. I believe what happened is that whomever submitted the Traditional Chinese issue in GitHub didn't supply the localized version of the language name, so I used Google Translate.

@all-contributors please add @toto6038 for translations
