### ISSUE TITLE
Add info on migration to home page FAQ

### ISSUE THREAD

**Issue by EzequielBruni** [rocky-linux/rockylinux.org-gatsby#4]
## Description
Add a bit to the home page FAQ to address migration from CentOS to Rocky Linux. It's the most common question I've personally seen in all of the community spaces.

I was going to fork / pull request, but I can't actually find the file with the FAQ content.

**Comment by hbjydev** [comment]
Removing from the RC1 milestone, because this will be something we need closer to GA, once we've got a tried and tested CentOS -> RL conversion process fleshed out.

**Comment by FoggyMtnDrifter** [comment]
Closing this for now since this will be a part of the site redesign.
