### ISSUE TITLE
Undeliverable email address listed

### ISSUE THREAD

**Issue by shujisado** [rocky-linux/rockylinux.org-gatsby#416]
This page lists sponsors@resf.org, but that is an unused address; it should be changed to sponsor@rockylinux.org .

https://github.com/rocky-linux/rockylinux.org/blob/8ca080d54b22de4fa0dc2d5af2e4534b8372f656/src/pages/sponsors.js#L209

**Comment by NeilHanlon** [comment]
Hi @shujisado  - Thank you for pointing this out!

I've just gone ahead and added that as an alias for the mailbox in our system.

Best,
Neil
