### ISSUE TITLE
Publish Raspberry Pi 9 Link

### ISSUE THREAD

**Issue by skip77** [rocky-linux/rockylinux.org-gatsby#417]
We have a new Raspberry Pi image for Rocky 9, with accompanying README and checksums:   https://download.rockylinux.org/pub/sig/9/altarch/aarch64/images/

I'd like to get this published in the little table above the current Rocky Rpi 8 image on the alternative images download page:   https://rockylinux.org/alternative-images .

Basically, it should be updated with a new row, and there should be some kind of indicator on which row is 8, and which is 9.  The links for the 9 image all have counterparts with the Rocky Rpi 8 image.

Thanks!

-Skip Grube

**Comment by FoggyMtnDrifter** [comment]
Added, closing
