### ISSUE TITLE
Rocky Linux 9 keys missing from keys page

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/rockylinux.org-gatsby#418]
#### Description

The page at rockylinux.org/keys is not up to date. It only mentions Rocky Linux 8 related keys.

#### Screenshots

![image](https://user-images.githubusercontent.com/11469736/183268512-18054a92-1463-4081-b983-ebd2a2bff0d5.png)

**Comment by FoggyMtnDrifter** [comment]
Thanks for the heads up! Will get this fixed ASAP.

**Comment by FoggyMtnDrifter** [comment]
Updated, closing.
