### ISSUE TITLE
404 Page Has Color Issues in Dark Mode

### ISSUE THREAD

**Issue by NebraskaCoder** [rocky-linux/rockylinux.org-gatsby#420]
#### Description

In dark mode, the 404 page has coloring issues where black text is displayed on a dark background.

I have already made a fix and just need the approval to submit a PR for this.

#### Screenshots

This is the bug:
![Bug With Black Text](https://user-images.githubusercontent.com/64073162/184510787-56eed7dd-1412-49c3-9dc4-22b93874d2a1.png)

This is the fix:
![Fixed Bug](https://user-images.githubusercontent.com/64073162/184510795-480d1103-67b5-4acd-9c34-02ecf57d8692.png)

#### Files

`src/pages/404.js` and `src/images/shrug.svg` are the files that affect this.

#### To Reproduce

Just go to a non-existent page.

**Comment by FoggyMtnDrifter** [comment]
Thanks! Go ahead and open your PR.

**Comment by NebraskaCoder** [comment]
I also found a bug where the dark background wasn't full screen. I added that to my PR.

**Comment by FoggyMtnDrifter** [comment]
Looks like it got merged, closing
