### ISSUE TITLE
Request a correct OVT 11.3.5 release

### ISSUE THREAD

**Issue by Winnie81** [rocky-linux/rockylinux.org-gatsby#422]
From https://github.com/vmware/open-vm-tools/pull/513/, it seems that Rocky Linux put proposed changes for GuestID.

These changes (https://github.com/vmware/open-vm-tools/pull/513/files) modified:
    guest_os.h
    guest_os_tables.h
    hostinfoPosix.c

Were these changes included in your 11.3.5 open-vm-tools packages? If so, could you please remove these changes and correct to the 11.3.5 OVT packages? 

Just a reminder,  please do not have any alterations in a 12.0.x OVT release or the upcoming 12.1.0 OVT. Thanks a lot.

**Comment by nazunalika** [comment]
Hello.

Please report this issue to https://bugs.rockylinux.org and describe the issue with the changes that were made (by request of community members), with applicable logs, screenshots, and so on, and alternative options if applicable. Open vm tools will not receive any changes in the 12 release and beyond based the request of the vmware engineers and release notes of version 12.
