### ISSUE TITLE
`yum install antlr-C++ antlr-tool`  doesn't work on RockyLinux 8, even with Powertools repository enabled

### ISSUE THREAD

**Issue by thebaptiste** [rocky-linux/rockylinux.org-gatsby#434]
#### Description

`yum install antlr-C++ antlr-tool`  doesn't work on RockyLinux 8, even with Powertools repository enabled

`wget https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/antlr-C++-2.7.7-56.module+el8.3.0+74+855e3f5d.x86_64.rpm` (the download url given in [https://rockylinux.pkgs.org/9/rockylinux-appstream-x86_64/antlr-tool-2.7.7-68.el9.noarch.rpm.html](https://rockylinux.pkgs.org/9/rockylinux-appstream-x86_64/antlr-tool-2.7.7-68.el9.noarch.rpm.html) doesn't work either

But `wget https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os/Packages/a/antlr-C++-2.7.7-56.module+el8.3.0+74+855e3f5d.x86_64.rpm` is ok.

**Comment by brianclemens** [comment]
Hi @thebaptiste, the best place to ask for support is on https://chat.rockylinux.org, the forums at https://forums.rockylinux.org, or the mailing lists. This repository is just for the Rocky Linux homepage.
