### ISSUE TITLE
Translation typo on Frequently Asked Questions

### ISSUE THREAD

**Issue by becker** [rocky-linux/rockylinux.org-gatsby#442]
#### Description

The pt_BR translation of  **About** > **Frequently Asked Questions**  has a typo:
[https://rockylinux.org/pt_BR/faq](https://rockylinux.org/pt_BR/faq)

**Current**: `Preguntas`
**Correct**: `Perguntas`

#### Files

https://github.com/rocky-linux/rockylinux.org/blob/bf40cb7314df31d2e48f811771bcc93987a7c529/i18n/locales/pt_BR/faq.json#L2

**Comment by FoggyMtnDrifter** [comment]
Thanks for the report! Please flag this issue in Crowdin (link in CONTRIBUTING.md) or make the changes if you haven't already and it will be merged in as soon as possible.
