### ISSUE TITLE
Add MontaVista to Sponsors page

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#45]
Hi there,

[MontaVista](https://www.mvista.com/) is a new Principal Sponsor. Can we please add their logo to the landing page + Sponsors page? Here's a quote to use for them:

> MontaVista Software is the leader in embedded commercial Linux, supporting MontaVista CGX, Yocto Project®, CentOS and Rocky Linux. MontaVista offers Open Source Software expertise, commercial-quality Linux distros, cost-effective maintenance and support for 10+ year life-cycles.

https://www.dropbox.com/s/5x5nwwf07f7de8u/MVLogos.zip?dl=0

**Comment by NebraskaCoder** [comment]
I can take a look and push a pull request for this.
