### ISSUE TITLE
Rocky 9 cloud images are not listed on cloud-images page

### ISSUE THREAD

**Issue by neirbowj** [rocky-linux/rockylinux.org-gatsby#450]
#### Description

When seeking the AMI ID (not AWS Marketplace) for the official project images for AWS in various regions and for various architectures, the [Cloud images](https://rockylinux.org/cloud-images/) page does not include any images for Rocky 9 at all, which was released over three months ago.

A related criticism is that the [Download](https://rockylinux.org/download) page organizes information in such a way that the non-ISO options, including "Cloud images" are very likely to be overlooked.

#### Screenshots
<img width="978" alt="Screen Shot 2022-10-26 at 18 15 21" src="https://user-images.githubusercontent.com/1879063/198148844-b3f0ef04-2a88-4fb2-b065-399436ba3f2a.png">

#### Files

I don't know.

#### To Reproduce

1. Visit https://rockylinux.org/cloud-images/
2. Try to find a Rocky Linux 9 entry in the table
3. Google for "rocky linux 9 ami" and variations thereof
4. Feel sad

**Comment by brianclemens** [comment]
@NeilHanlon I'm browsing through the AWS dashboard, how can I get a list of our AMIs? In the EC2 portal I only see one, and in the EC2 Image Builder portal I'm unable to load anything.

I know the goal is to automate this but I figure I can just do some quick manual data entry until we have that ready.

**Comment by NeilHanlon** [comment]
Check https://github.com/rocky-linux/rockylinux.org/tree/json-update

For gathering the IDs, we can use some variation of

```
aws ec2 describe-images --owners 792107900819
```

The reason  you cannot see them in the account you're on is because they're stored in a different AWS account for #security

**Comment by NeilHanlon** [comment]
cc @ressonix @NebraskaCoder

**Comment by brianclemens** [comment]
Gotcha, thanks @NeilHanlon!

**Comment by brianclemens** [comment]
@neirbowj apologies for the delay. This is fixed with #484

@ressonix @NebraskaCoder I updated the dataset and merged it a bit prematurely, it breaks the nice "deploy" link but I think having the full list of images is more important. Just a head's up that I broke that.

@NeilHanlon here's the script I used, I'll throw it in the website CI later or something:
```bash
#!/bin/bash

# AWS ID we use to store our images
owner_id=792107900819

# Array to hold all the AMI information
all_ami_info=()

# Iterate through each region
for region in `aws ec2 describe-regions --output json | jq -r '.Regions[].RegionName'`
do
    # Get the AMI IDs and descriptions for the owner in this region
    ami_ids=$(aws ec2 describe-images --owners $owner_id --region $region --output json | jq -r '.Images[].ImageId')

    # Iterate through each AMI ID
    while read -r ami_id; do
        # Get the AMI details
        ami_details=$(aws ec2 describe-images --image-ids $ami_id --region $region --output json)

        # Extract the AMI architecture
        architecture=$(echo $ami_details | jq -r '.Images[0].Architecture')

        # Extract the AMI version
        version=$(echo $ami_details | jq -r '.Images[0].Name' | grep -o '[0-9]\+\.[0-9]\+' | head -1)

        # Create a JSON object for this AMI
        ami_info=$(jq -n --arg version "$version" --arg provider "AWS" --arg region "$region" --arg architecture "$architecture" --arg imageid "$ami_id" --arg deploylink "https://console.aws.amazon.com/ec2/v2/home?region=$region#LaunchInstanceWizard:ami=$ami_id" '{version: $version, provider: $provider, region: $region, architecture: $architecture, imageid: $imageid, deploylink: $deploylink}')

        # Add the AMI information to the array
        all_ami_info+=($ami_info)
    done <<< "$ami_ids"
done

# Convert the array to JSON and print it
echo "${all_ami_info[@]}" | jq -s '.'
```

**Comment by NeilHanlon** [comment]
I'll munge that into the empanadas repo, if you want. 

(https://git.resf.org/sig_core/toolkit/src/branch/devel/sync/propagate-image.sh)

**Comment by brianclemens** [comment]
Sounds good to me 👍
