### ISSUE TITLE
Add Mastodon Share Link to Blog Pages

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [rocky-linux/rockylinux.org-gatsby#460]
Due to the de-centralized nature of Mastodon, we'd need to know the instance a user is running on in order to properly use the sharing feature. Looks like this may be achievable with this: https://github.com/justinribeiro/share-to-mastodon

**Comment by brianclemens** [comment]
Temporarily accomplished with 9d69f48e56b848db2718b51d69bca800c56637a6 though the system you linked seems more elegant, so I'll leave the issue open in case you want to replace it.
