### ISSUE TITLE
Rocky Raspberry Pi 8.7 Links Update

### ISSUE THREAD

**Issue by skip77** [rocky-linux/rockylinux.org-gatsby#463]
Need to update Raspberry Pi 8 to the latest image links located in:  https://dl.rockylinux.org/pub/sig/8/altarch/aarch64/images/

The README, image, and shasum files should all be updated from the Rocky Alt. Images download page.

Thank you!

-Skip

**Comment by NebraskaCoder** [comment]
Addressed with PR #468
