### ISSUE TITLE
Rocky 9 download links broken on rockylinux.org

### ISSUE THREAD

**Issue by DamnedElric** [rocky-linux/rockylinux.org-gatsby#464]
The [download page](https://rockylinux.org/download) has download links for 9.0, these are all broken. The directory on the download server only contains 9.1 images.

e.g. "x86_64 minimal" links to https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.0-20220805.0-x86_64-minimal.iso but should link to https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.1-x86_64-minimal.iso

I don't know how the infrastructure is setup, it's possible that this is a CDN/mirror issue instead of just a broken link.

**Comment by NeilHanlon** [comment]
Hi @DamnedElric  - I am not able to replicate what you are seeing. Can you please try a 'Hard' refresh of the browser page with Ctrl+F5 e.g.?

If I look at the timing of our release announcement, the website change went out around ~7:30 Eastern, and this ticket was created before that. To that end, I believe #465 resolves this.

Best,
Neil

**Comment by DamnedElric** [comment]
Correct, seems to be fixed now, thanks
