### ISSUE TITLE
Broken link to Raspberry Pi readme.txt for Rocky 9 on Alternative Images page

### ISSUE THREAD

**Issue by historicbruno** [rocky-linux/rockylinux.org-gatsby#480]
#### Description

The readme link for Rocky 9 Raspberry Pi aarch64 leads to a 404 Not Found error.

#### To Reproduce

Visit https://rockylinux.org/alternative-images, the link to the Rocky 9 Raspberry Pi readme is currently https://download.rockylinux.org/pub/sig/9/altarch/aarch64/images/README.txt, but the file itself is lower-case `readme.txt`

**Comment by brianclemens** [comment]
Fixed in cd5277edd15dc2e8ccbf43e5a11e291b12ce000d
