### ISSUE TITLE
cloud-images page should include the date published and/or name of the AMIs

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/rockylinux.org-gatsby#500]
#### Description

We may publish several Z-stream (8.7.z, 9.1.z) images into AWS for a variety of reasons. We should display the date of the image or the name of the AMI (which includes the date) so users can see which is the latest version to select that.

https://rockylinux.org/cloud-images/

**Comment by NeilHanlon** [comment]
![image](https://user-images.githubusercontent.com/680198/222190265-5ca4e725-deac-43e1-a8c4-c4715c17ad3c.png)

**Comment by tcooper** [comment]
@NeilHanlon see https://github.com/rocky-linux/rockylinux.org/issues/492

**Comment by NeilHanlon** [comment]
TY! Closing as duplicate of #492
