### ISSUE TITLE
Rocky Torrent Downloads Fail

### ISSUE THREAD

**Issue by zaxlofful** [rocky-linux/rockylinux.org-gatsby#529]
#### Description
All Torrent links on the Rocky Downloads page fail.

#### Screenshots
![image](https://github.com/rocky-linux/rockylinux.org/assets/33877007/649383ef-0d44-454a-a176-b00f00860ac3)

#### To Reproduce
Attempt to download one of the torrent files from the main Rocky download page :

https://rockylinux.org/download/

**Comment by NeilHanlon** [comment]
This is likely a cache issue in our cdn. please give me a few hours and I will issue a purge request across all points of presence

**Comment by zaxlofful** [comment]
The torrents for Rocky 9 are working now, but the ones for Rocky 8 are still not working.

**Comment by zaxlofful** [comment]
Also, the ISO's don't have their version number in them. So downloading 8/9 results in the same named file.

**Comment by brianclemens** [comment]
Fixed with 777534f

**Comment by zaxlofful** [comment]
Aren't those the wrong versions? 9.2 and 8.8 are the latest....
