### ISSUE TITLE
Update Raspberry Pi links on Alternative Images page

### ISSUE THREAD

**Issue by skip77** [rocky-linux/rockylinux.org-gatsby#534]
#### Description

I need to get the raspberry pi download links updated on this page:

https://rockylinux.org/alternative-images/

We are moving to a "-latest" naming scheme, so we can just push files and not have to update the link each time.

The links should look like this for 8 and for 9 (spelling/capitalization in the links is exact!):

Rocky 8:
Image: https://dl.rockylinux.org/pub/sig/8/altarch/aarch64/images/RockyLinuxRpi_8-latest.img.xz
Checksum: https://dl.rockylinux.org/pub/sig/8/altarch/aarch64/images/RockyLinuxRpi_8-latest.img.xz.sha256sum
Readme:  https://dl.rockylinux.org/pub/sig/8/altarch/aarch64/images/README.txt

Rocky 9:
Image:  https://dl.rockylinux.org/pub/sig/9/altarch/aarch64/images/RockyLinuxRpi_9-latest.img.xz
Checksum:  https://dl.rockylinux.org/pub/sig/9/altarch/aarch64/images/RockyLinuxRpi_9-latest.img.xz.sha256sum
Readme: https://dl.rockylinux.org/pub/sig/9/altarch/aarch64/images/README.txt

I'd like to get the Alternative Images page updated with these permanent links ASAP.

Thanks!

-Skip

**Comment by brianclemens** [comment]
Fixed via 58817de
