### ISSUE TITLE
`mirrors.rockylinux.org` static resources are served absolutely wrong

### ISSUE THREAD

**Issue by JounQin** [rocky-linux/rockylinux.org-gatsby#565]
#### Description

5.8MB css blocking the first paint without any cache!

#### Screenshots

<img width="907" alt="企业微信20231121-134048@2x" src="https://github.com/rocky-linux/rockylinux.org/assets/8336744/1a2b2955-934e-47c2-945f-179898585ca7">

#### Files

All static resources

#### To Reproduce

https://mirrors.rockylinux.org/mirrormanager/

**Comment by NebraskaCoder** [comment]
The mirror manager is not handled by this repo. I'm closing this issue as there is nothing that can be done in this repo, but I'll see if I can pass this along to the proper owners.

**Comment by JounQin** [comment]
Yeah, but I found nowhere else to raise the issue.

**Comment by NebraskaCoder** [comment]
I just edited my comment. I have passed along the message.

**Comment by JounQin** [comment]
Thanks, is `mirrors` website open sourced?

**Comment by NebraskaCoder** [comment]
I don't see the code in our org:rocky-linux repos. I'm not familiar with it myself. You could try asking in our ~infrastructure channel on Mattermost (or forums or our Reddit).
