### ISSUE TITLE
Donations page is broken

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#59]
External users are confirming that the donate page is broken, can you please take a look?

**Comment by mstg** [comment]
It seems like the donation page relies on the generated stylesheet.
```
<link href="https://rockylinux.org/styles.56bd1f5b1d880faf5355.css" rel="stylesheet" />
```

For the latest version that stylesheet is now named `styles.b8ec5ea3d7ea821033a3.css`.
It may not be a good idea to rely on a file that changes each deploy, so is it possible to use a static filename with a cache busting query?

**Comment by FoggyMtnDrifter** [comment]
This has been fixed, I simply included the styles in the same file.

**Comment by hbjydev** [comment]
@mstg We're sort of at the mercy of Gatsby when it comes to this, unless one of the plugins it provides will let us spit out a cacheable version of the file instead of the auto-generated one it currently makes.

**Comment by NeilHanlon** [comment]
@hbjydev I'm not sure how gatsby is configured, but is there perhaps some generic URL we can use that doesn't put styles.<sha>.css, but rather `styles.css?v=<sha>` ?

In the CDN, that URI will be cached, but also it should return just some default stylesheet without the queryparam. The SHA is really just a cachebuster for the stylesheet, and ideally that param should be at the end.

I'm not familiar enough w/ gatsby to say if there's maybe some config that controls the URI generated for CSS?
