### ISSUE TITLE
i18n on Posts index is broken

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rockylinux.org-gatsby#6]
## Describe the bug
On the localised site, if you go to the post index, it will send you back to the homepage straight away.

## To Reproduce
If you go to `/<lang>/posts`, it redirects you to the homepage.

## Expected behavior
It should redirect you to the regular posts index (although the posts won't be localised -- far too much work involved)

For example, `GET /es/posts 302 /posts`

## Screenshots
N/a

## Device Information
N/a

**Additional context (Please delete this if there's no additional context):**
Final work for issue rocky-linux/rockylinux.org-hugo#133

**Comment by FoggyMtnDrifter** [comment]
This is fixed in the new Gatsby version of the website. :))
