### ISSUE TITLE
Donate link in footer of Sponsors page is bad, yields 404

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#60]
When trying to reach the Sponsors page from the Donate page via 'Sponsors' URL in footer, a 404 is yielded due to a bad URL: https://donate.rockylinux.org/sponsors/

Instead, should be: https://rockylinux.org/sponsors/

**Comment by jorp** [comment]
1. navigate to 'donate' in the top navbar: https://rockylinux.z2systems.com/np/clients/rockylinux/donation.jsp
2. click 'sponsors' in the footer navbar: https://donate.rockylinux.org/sponsors/ :warning: 

 :warning: https://donate.rockylinux.org/sponsors/  :arrow_right: https://rockylinux.org/sponsors/ :heavy_check_mark:
