### ISSUE TITLE
Add 280c blurb for Mattermost

### ISSUE THREAD

**Issue by rlhennig** [rocky-linux/rockylinux.org-gatsby#69]
The Mattermost team just provided the following:

> Mattermost is an open source messaging solution made for organizations with the highest security requirements. As big believers in the power of open source, Mattermost is thrilled to partner with RESF to help bring an enterprise-grade distribution of Linux to the tech community.

Can we please add that for them next to their logo on the Partners page? Thanks

**Comment by hbjydev** [comment]
Will go live with the next site release.
