### ISSUE TITLE
Create pages Get Involved and Get In Touch

### ISSUE THREAD

**Issue by domingoruiz** [rocky-linux/rockylinux.org-gatsby#8]
Hi. I have the idea that cretate a Get Involved page and Get In Touch page. If you agree with the idea, I could take care of it and propose a pull request. If you agree, it would be good if you assigned me the issue. I am also all ears for proposals for those pages.

Thanks you.

Bye.

**Comment by domingoruiz** [comment]
I think the site should have simply been Bootstrap. As you already know, simple things are easy to maintain. Right now we use Hugo, Nodejs for Hugo, the themes, too many things that can go wrong when we could have a fantastic website using just Bootstrap.

**Comment by FoggyMtnDrifter** [comment]
Are we good to close this @hbjydev since we're using the Wiki/Docs side of things for this stuff at the moment?

**Comment by hbjydev** [comment]
Yeah, I think so. Closing...
