### ISSUE TITLE
Swedish Translation of the Partners page

### ISSUE THREAD

**Issue by bittin** [rocky-linux/rockylinux.org-gatsby#98]
[partners_sv.jsx.zip](https://github.com/rocky-linux/rockylinux.org/files/6412973/partners_sv.jsx.zip)

**Comment by FoggyMtnDrifter** [comment]
Hey there! You will want to update the i18n files and make a PR of the translation strings for the appropriate file. You can find those [here](https://github.com/rocky-linux/rockylinux.org/tree/main/src/i18n).
