### ISSUE TITLE
Make All Pages Translatable

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [rocky-linux/rockylinux.org-gatsby#99]
## Description

Right now, some pages haven't really been made translatable via i18n, so we'll need to eventually start moving strings into the i18n for those pages. Note that we won't be translating blog posts or press links, just page content.

**Comment by ofaruksahintr** [comment]
Shall we use i18n namespace for per page? [i18n ns](https://www.i18next.com/principles/namespaces#technical-editorial-reasons)
for ex. structure;
```
en/
  translation.js -- (common)
  index.js
  download.js
  faq.js
  .....
```
Edited:
Linked to PR #110
